apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multi-deploy
  name: multi-deploy
  namespace: q30
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multi-deploy
    spec:
      containers:
      - image: nginx:latest
        name: web
        ports:
        - containerPort: 80
        resources: {}
      - image: busybox:latest
        name: metrics
        command: ["/bin/sh","-c", "while true; do echo metrics; sleep; done"]
status: {}
