apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-with-sidecar
  name: web-with-sidecar
spec:
  containers:
  - image: nginx:latest
    name: web-with-sidecar
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
      - mountPath: /var/log/nginx
        name: shared-logs
  - image: busybox:latest
    command: ["sh", "-c", "while true; do wget -q -O - http://localhost:80 >> /var/log/nginx/access.log; sleep 5; done"]
    name: sidecar
    resources: {}
    volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs
  volumes:
    - name: shared-logs
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
