apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: compute-quota
  namespace: q60
spec: 
  hard:
    requests.cpu: "1"
    limits.cpu: "2"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
status: {}
