apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hostpath-pod
  name: hostpath-pod
spec:
  containers:
  - image: nginx:latest
    name: hostpath-pod
    resources: {}
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: hostpath-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: hostpath-volume
      hostPath:
        path: /data/web
        type: DirectoryOrCreate
status: {}
