apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hostpath-pod
  name: hostpath-pod
spec:
  containers:
  - image: nginx:latest
    name: hostpath-pod
    volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: example-volume
    resources: {}
  volumes:
  - name: example-volume
    hostPath:
      path: /data/web
      type: DirectoryOrCreate
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
