apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tracked-app
  name: tracked-app
  namespace: q38
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tracked-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tracked-app
    spec:
      containers:
      - image: nginx:1.20
        name: nginx
        resources: {}
status: {}
