apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: crashing-pod
  namespace: q28
spec:
  containers:
  - command:
    - sh
    - -c
    - echo starting app; sleep 3600
    image: busybox:latest
    imagePullPolicy: Always
    name: app
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-52dvr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-52dvr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-05-18T12:18:19Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-05-18T12:18:15Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-05-18T12:18:20Z"
    message: 'containers with unready status: [app]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-05-18T12:18:20Z"
    message: 'containers with unready status: [app]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-05-18T12:18:15Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://36caca113f318bf0c8602a839c652766d56a47e202fc19c36340e90eb6be0de4
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
    lastState:
      terminated:
        containerID: containerd://f74e50980466cbfaa61ca07fe62d736cc789918f294a010fa2bc37cfc2e39651
        exitCode: 1
        finishedAt: "2026-05-18T12:19:01Z"
        reason: Error
        startedAt: "2026-05-18T12:19:01Z"
    name: app
    ready: false
    resources: {}
    restartCount: 4
    started: false
    state:
      terminated:
        containerID: containerd://36caca113f318bf0c8602a839c652766d56a47e202fc19c36340e90eb6be0de4
        exitCode: 1
        finishedAt: "2026-05-18T12:19:49Z"
        reason: Error
        startedAt: "2026-05-18T12:19:49Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 10
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-52dvr
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.18.0.2
  hostIPs:
  - ip: 172.18.0.2
  observedGeneration: 1
  phase: Running
  podIP: 10.244.1.2
  podIPs:
  - ip: 10.244.1.2
  qosClass: BestEffort
  startTime: "2026-05-18T12:18:15Z"
