apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmV4YW1wbGUuY29tIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InNlY3JldDEyMyIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJhdXRoIjoiWVdSdGFXNDZjMlZqY21WME1USXoifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: my-registry-secret
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: registry-pod
  name: registry-pod
  namespace: q69
spec:
  containers:
  - image: nginx:latest
    name: my-registry-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
  - name: my-registry-secret
status: {}
