apiVersion: v1
kind: Pod
metadata:
  labels:
    run: log-aggregator
  name: log-aggregator
spec:
  containers:
  - image: busybox:latest
    name: writer
    command: ["sh", "-c", "while true; do echo $(date) INFO log entry >> /var/log/app/output.log; sleep 5; done"]
    volumeMounts:
      - mountPath: /var/log/app
        name: shared-logs
    resources: {}
  - image: busybox:latest
    name: reader
    command: ["sh", "-c", "tail -f /var/log/app/output.log"]
    volumeMounts:
      - mountPath: /var/log/app
        name: shared-logs
    resources: {}
  volumes:
  - name: shared-logs
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
