apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shared-vol-pod
  name: shared-vol-pod
spec:
  containers:
  - image: busybox:latest
    name: writer
    command: ["sh", "-c", "while true; do date >> /data/output.txt; sleep 5; done"]
    resources: {}
    volumeMounts:
        - name: shared-data
          mountPath: /data
  - image: busybox:latest
    name: reader
    volumeMounts:
        - name: shared-data
          mountPath: /data
    resources: {}
  volumes:
  - name: shared-data
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

status: {}
