apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: env-app
  name: env-app
  namespace: q41
spec:
  replicas: 2
  selector:
    matchLabels:
      app: env-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: env-app
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
        envFrom:
          - configMapRef:
              name: app-config
status: {}
