apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  completions: 5
  parallelism: 2
  template:
    metadata: {}
    spec:
      restartPolicy: "Never"
      containers:
      - image: busybox:latest
        name: batch-job
        command: ["sh", "-c", "echo Processing batch item"]
        resources: {}
      restartPolicy: Never
status: {}
