apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nonroot-pod
  name: nonroot-pod
  namespace: q57
spec:
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    runAsGroup: 3000
  containers:
  - image: nginx:latest
    name: nonroot-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
