apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: broken-app
  name: broken-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-app
  strategy: {}
  template:
    metadata:
      labels:
        app: broken-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
