apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"web-svc","namespace":"q12"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"wrongapp"}}}
  creationTimestamp: "2026-05-04T17:54:42Z"
  name: web-svc
  namespace: q12
  resourceVersion: "3415"
  uid: 2fb32f73-1a78-4d9e-98ec-831b5e99324d
spec:
  clusterIP: 10.96.237.24
  clusterIPs:
  - 10.96.237.24
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wrongapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
