apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rolling-app
  name: rolling-app
  namespace: q35
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rolling-app
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rolling-app
    spec:
      containers:
      - image: nginx:1.20
        name: nginx
        resources: {}
status: {}
