apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: triple-probe-pod
  name: triple-probe-pod
  namespace: q50
spec:
  containers:
  - image: nginx:latest
    name: triple-probe-pod
    ports:
    - containerPort: 80
    resources: {}
    startupProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 10
      failureThreshold: 30
    livenessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 15
    readinessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
