apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"api-deploy","namespace":"q10"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"api-deploy"}},"template":{"metadata":{"labels":{"app":"api-deploy"}},"spec":{"containers":[{"image":"nginx:latest","name":"api","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2026-05-04T17:35:34Z"
  generation: 1
  name: api-deploy
  namespace: q10
  resourceVersion: "1313"
  uid: 0ad0ee1f-3f59-4211-b0a6-14aa3d38d1ba
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-deploy
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: api
        readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /ready
              port: 8080
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2026-05-04T17:36:20Z"
    lastUpdateTime: "2026-05-04T17:36:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-05-04T17:35:34Z"
    lastUpdateTime: "2026-05-04T17:36:20Z"
    message: ReplicaSet "api-deploy-67bf87bf7f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  terminatingReplicas: 0
  updatedReplicas: 2
