apiVersion: v1
kind: Pod
metadata:
  labels:
    run: resource-pod
  name: resource-pod
spec:
  containers:
  - image: nginx:latest
    name: resource-pod
    resources:
      requests:
          cpu: 100m
          memory: 128Mi
      limits:
          cpu: "1"
          memory: 2Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
