apiVersion: v1
kind: Pod
metadata:
  labels:
    run: request-pod
  name: request-pod
spec:
  containers:
  - image: nginx:latest
    name: request-pod
    resources:
        requests:
          cpu: 250m
          memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
