apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fsgroup-pod
  name: fsgroup-pod
  namespace: q59
spec:
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
  containers:
  - image: busybox:latest
    name: fsgroup-pod
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
      - name: empty-dir
        mountPath: /data
    resources: {}
  volumes:
    - name: empty-dir
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
